#!/usr/bin/env python3
"""Turns an 8-pixel-wide BDF font with CP437 encodings (Spleen's cp437/spleen-8x16-ibm-437.bdf)
into core/vc_font.c: 256 glyphs, one byte per row, most significant bit leftmost.

    python3 bdf2c.py spleen-8x16-ibm-437.bdf > ../core/vc_font.c
"""
import sys


def main(path):
    height = 16
    glyphs = {}
    ascent = None
    lines = open(path, encoding='latin-1').read().splitlines()
    i = 0
    while i < len(lines):
        words = lines[i].split()
        if words and words[0] == 'FONTBOUNDINGBOX':
            height = int(words[2])
            ascent = int(words[2]) + int(words[4])  # rows above the baseline
        if words and words[0] == 'STARTCHAR':
            code = None
            bbx = None
            while not lines[i].startswith('BITMAP'):
                w = lines[i].split()
                if w[0] == 'ENCODING':
                    code = int(w[1])
                elif w[0] == 'BBX':
                    bbx = [int(v) for v in w[1:5]]
                i += 1
            i += 1
            rows = []
            while not lines[i].startswith('ENDCHAR'):
                rows.append(int(lines[i][:2], 16))
                i += 1
            if code is not None and 0 <= code < 256:
                w, h, xoff, yoff = bbx
                cell = [0] * height
                top = ascent - (h + yoff)  # the glyph's first row in the cell
                for r, bits in enumerate(rows):
                    if 0 <= top + r < height:
                        cell[top + r] = (bits >> xoff) & 0xFF
                glyphs[code] = cell
        i += 1
    out = sys.stdout
    out.write('/* Generated by vidcard/tools/bdf2c.py from Spleen 8x16 (cp437/spleen-8x16-ibm-437.bdf).\n')
    out.write(' * Spleen: Copyright (c) 2018-2024, Frederic Cambus. BSD 2-Clause license:\n')
    out.write(' * https://github.com/fcambus/spleen -- see NOTICE.md. */\n')
    out.write('#include "vc.h"\n\n')
    out.write('const uint8_t vc_font8x16[256 * 16] = {\n')
    for code in range(256):
        cell = glyphs.get(code, [0] * height)
        out.write('    ' + ', '.join('0x%02X' % b for b in cell) + ', /* %d */\n' % code)
    out.write('};\n')


if __name__ == '__main__':
    main(sys.argv[1])
