#!/usr/bin/env python3
"""Generates pa_itab.asm, pugasm's operation table, from lwasm's own table
(lwtools-4.20/lwasm/instab.c), so the two assemblers know exactly the same
mnemonics, opcodes and directives.

    python gen_itab.py [path/to/instab.c]      (writes pa_itab.asm next to this file)

Only what lwasm accepts under its default pragmas is kept: 6800-compatibility,
6809/6309 "convenience" and emulator-extension entries are dropped, and for a
name listed more than once the first remaining entry wins (lwasm's lookup takes
the first match). The entries are sorted by name for a binary search.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "lwtools-4.20", "lwasm", "instab.c")

FLAGBITS = {
    "lwasm_insn_cond": 0x01,
    "lwasm_insn_endm": 0x02,
    "lwasm_insn_setsym": 0x04,
    "lwasm_insn_is6309": 0x08,
    "lwasm_insn_struct": 0x10,
    "lwasm_insn_setdata": 0x20,
    "lwasm_insn_is6809": 0x40,
    "lwasm_insn_org": 0x80,
    "lwasm_insn_normal": 0,
}
DROP = {"lwasm_insn_is6800", "lwasm_insn_is6809conv", "lwasm_insn_is6309conv", "lwasm_insn_isemuext"}

# lwasm parse function -> pugasm handler class (CL_* in pa_itab.asm). Classes
# below $40 are instructions (their four opcodes follow the entry); the rest are
# directives. Directives pugasm doesn't implement get CL_UNSUP ("not supported").
CLASSES = [
    ("insn_parse_inh", "INH"), ("insn_parse_gen0", "GEN0"), ("insn_parse_gen8", "GEN8"),
    ("insn_parse_gen16", "GEN16"), ("insn_parse_gen32", "GEN32"), ("insn_parse_imm8", "IMM8"),
    ("insn_parse_indexed", "INDEXED"), ("insn_parse_relgen", "REL"), ("insn_parse_rlist", "RLIST"),
    ("insn_parse_rtor", "RTOR"), ("insn_parse_tfmrtor", "TFMRTOR"), ("insn_parse_tfm", "TFM"),
    ("insn_parse_bitbit", "BITBIT"), ("insn_parse_logicmem", "LOGICMEM"),
]
DIRECTIVES = [
    "org", "equ", "set", "setdp", "fcb", "fdb", "fqb", "fcc", "fcn", "fcs", "rmb", "rmd", "rmq",
    "zmb", "zmd", "zmq", "fill", "align", "end", "include", "includebin", "ifeq", "ifne", "ifgt",
    "ifge", "iflt", "ifle", "ifdef", "ifndef", "else", "endc", "macro", "endm", "struct",
    "endstruct", "section", "endsection", "export", "import", "extern", "extdep", "error",
    "warning", "noop", "pragma", "starpragma",
]
INSN_CLASS = {fn: i + 1 for i, (fn, _) in enumerate(CLASSES)}
DIR_CLASS = {name: 0x40 + i for i, name in enumerate(DIRECTIVES)}
UNSUP = 0x7F


def directive_class(fn):
    name = fn.replace("pseudo_parse_", "")
    aliases = {"starpragmapush": "starpragma", "starpragmapop": "starpragma"}
    name = aliases.get(name, name)
    return DIR_CLASS.get(name, UNSUP)


def main():
    text = open(SRC, encoding="latin-1").read()
    row = re.compile(r'\{\s*"([^"]+)",\s*\{\s*([^}]*)\}\s*,\s*(\w+)\s*,\s*\w+\s*,\s*\w+\s*,\s*([^}]*?)\s*\}')
    seen = {}
    for m in row.finditer(text):
        name, ops, parse, flags = m.group(1), m.group(2), m.group(3), m.group(4)
        flagnames = [f.strip() for f in flags.split("|")]
        if any(f in DROP for f in flagnames):
            continue
        key = name.upper()
        if key in seen:
            continue
        ops = [int(o.strip(), 0) for o in ops.split(",")]
        bits = 0
        for f in flagnames:
            bits |= FLAGBITS[f]
        if parse in INSN_CLASS:
            cls = INSN_CLASS[parse]
        elif parse.startswith("pseudo_parse_"):
            cls = directive_class(parse)
        else:
            raise SystemExit("unknown parse function %s for %s" % (parse, name))
        seen[key] = (cls, bits, ops)

    names = sorted(seen)
    out = []
    w = out.append
    w("; ----------------------------------------------------------------------------")
    w("; pa_itab.asm -- GENERATED by gen_itab.py from lwtools-4.20/lwasm/instab.c;")
    w("; don't edit by hand. pugasm's operation table: every mnemonic and directive")
    w("; lwasm knows under its default pragmas, sorted by name for OPLOOKUP.")
    w(";")
    w("; An entry: the name's length, the name (upper case), the class (CL_*), the")
    w("; flags (OF_*), and for an instruction (class < CL_DIRECTIVE) its four opcodes,")
    w("; as lwasm orders them -- direct, indexed, extended, immediate; $FFFF = none;")
    w("; for a branch, the second is its offset size (8 or 16).")
    w("; ----------------------------------------------------------------------------")
    for i, (fn, cname) in enumerate(CLASSES):
        w("CL_%-11s equ  $%02X" % (cname, i + 1))
    w("CL_DIRECTIVE equ  $40")
    for name, cls in DIR_CLASS.items():
        w("CL_%-11s equ  $%02X" % (name.upper(), cls))
    w("CL_UNSUP     equ  $%02X             ; a directive pugasm doesn't do" % UNSUP)
    for f, b in FLAGBITS.items():
        if b:
            w("OF_%-11s equ  $%02X" % (f.replace("lwasm_insn_", "").upper(), b))
    w("OPCOUNT      equ  %d" % len(names))
    w("; The entries' addresses, in name order.")
    w("OPINDEX")
    for i, n in enumerate(names):
        w("            FDB  OP_%d" % i)
    for i, n in enumerate(names):
        cls, bits, ops = seen[n]
        chars = ",".join("'%s'" % c if c not in "'\\" else "$%02X" % ord(c) for c in n)
        w("OP_%-8d FCB  %d,%s" % (i, len(n), chars))
        w("            FCB  $%02X,$%02X" % (cls, bits))
        if cls < 0x40:
            w("            FDB  %s" % ",".join("$%04X" % (o & 0xFFFF) for o in ops))
    open(os.path.join(HERE, "pa_itab.asm"), "w", newline="\n").write("\n".join(out) + "\n")
    print("%d entries" % len(names))


if __name__ == "__main__":
    main()
