"""Writes simulator/tests/test_asm/pugasm/allops.asm (or allops9.asm with the
argument 6809): every mnemonic in pugasm's table for that CPU with each operand
form its class takes, plus backward and forward references. test_pugasm.cpp
assembles them with lwasm and pugasm and compares the two.

  python gen_allops.py [6309|6809]
"""
import os
import re
import sys

CPU = sys.argv[1] if len(sys.argv) > 1 else "6309"
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
tab = open(os.path.join(R, "pugasm", "pa_itab.asm")).read()
classes = {}
for m in re.finditer(r"^CL_(\w+)\s+equ\s+\$(\w+)", tab, re.M):
    classes[int(m.group(2), 16)] = m.group(1)
ops = []
for m in re.finditer(r"^OP_\d+\s+FCB\s+\d+,(.*)\n\s+FCB\s+\$(\w\w),\$(\w\w)", tab, re.M):
    name = "".join(eval(c) if c.startswith("'") else chr(int(c[1:], 16)) for c in m.group(1).split(","))
    if int(m.group(3), 16) & (0x40 if CPU == "6309" else 0x08):
        continue                        # the other CPU's
    ops.append((name, classes[int(m.group(2), 16)]))

addr = ["$10", "$1234", "<$20", ">$20", "bak", "fwd", "bakdp", "*+3",
        ",X", ",Y+", ",U++", ",-S", ",--X", "A,X", "B,Y", "D,U", "E,S", "F,X", "W,Y",
        "0,X", "5,Y", "-16,U", "15,S", "16,X", "-17,Y", "127,U", "-128,S", "128,X", "-129,Y", "1000,U",
        "<5,X", ">5,X", "<<3,Y", "bak,X", "fwd,X", "bakdp,Y",
        "[,X]", "[,Y++]", "[,--U]", "[A,X]", "[5,Y]", "[200,U]", "[$1234]", "[bak]", "[fwd]",
        "bak,PCR", "fwd,PCR", "*,PCR", "[bak,PCR]", "10,PC", "300,PC",
        ",W", ",W++", ",--W", "[,W]", "5,W", "[500,W]", "0,W"]
RTOR = ("A,B", "X,Y", "D,W", "CC,DP", "E,F", "0,A", "U,S", "PC,X")
if CPU == "6809":
    addr = [x for x in addr if x not in ("E,S", "F,X", "W,Y", ",W", ",W++", ",--W", "[,W]", "5,W", "[500,W]", "0,W")]
    RTOR = ("A,B", "X,Y", "CC,DP", "U,S", "PC,X", "D,X")
lines = ["* Generated by pugasm/gen_allops.py -- every operation, every operand form",
         "        ORG  $1000", "bakdp   EQU  $22", "bak     NOP"]
for name, cls in ops:
    if cls == "INH":
        lines.append("        %s" % name)
    elif cls in ("GEN0", "GEN8", "GEN16", "GEN32"):
        if cls != "GEN0":
            imm = {"GEN8": "#$12", "GEN16": "#$1234", "GEN32": "#$12345678"}[cls]
            lines.append("        %s %s" % (name, imm))
            if cls == "GEN8":
                lines.append("        %s #~1" % name)
        for a in addr:
            lines.append("        %s %s" % (name, a))
    elif cls == "INDEXED":
        for a in addr[8:]:
            lines.append("        %s %s" % (name, a))
    elif cls == "IMM8":
        lines.append("        %s #$12" % name)
    elif cls == "REL":
        n = len(lines)
        lines.append("nb%d     NOP" % n)
        for a in ("nb%d" % n, "nf%d" % n, "*", "*+10"):
            lines.append("        %s %s" % (name, a))
        lines.append("nf%d     NOP" % n)
    elif cls == "RLIST":
        lines.append("        %s A,B,X" % name)
        lines.append("        %s CC,D,DP,Y,PC" % name)
        lines.append("        %s %s" % (name, "S" if name.endswith("U") else "U"))
    elif cls == "RTOR":
        for a in RTOR:
            lines.append("        %s %s" % (name, a))
    elif cls == "TFMRTOR":
        lines.append("        %s A,B" % name)
    elif cls == "TFM":
        for a in ("X+,Y+", "X-,Y-", "X+,Y", "X,Y+", "D+,U+"):
            lines.append("        %s %s" % (name, a))
    elif cls == "BITBIT":
        lines.append("        %s A,1,2,$20" % name)
        lines.append("        %s CC,7,0,<$21" % name)
    elif cls == "LOGICMEM":
        for a in ("$20", "$1234", "5,X", "[,Y]", "bakdp"):
            lines.append("        %s #$12,%s" % (name, a))
        lines.append("        %s #$34;$21" % name)
lines += ["fwd     RTS", "        END"]
out = os.path.join(R, "simulator", "tests", "test_asm", "pugasm", "allops.asm" if CPU == "6309" else "allops9.asm")
open(out, "w", newline="\n").write("\n".join(lines) + "\n")
print(out, len(lines), "lines,", len(ops), "operations")
