; ----------------------------------------------------------------------------
; pa_itab.asm -- GENERATED by gen_itab.py from lwtools-4.20/lwasm/instab.c;
; don't edit by hand. pugasm's operation table: every mnemonic and directive
; lwasm knows under its default pragmas, sorted by name for OPLOOKUP.
;
; An entry: the name's length, the name (upper case), the class (CL_*), the
; flags (OF_*), and for an instruction (class < CL_DIRECTIVE) its four opcodes,
; as lwasm orders them -- direct, indexed, extended, immediate; $FFFF = none;
; for a branch, the second is its offset size (8 or 16).
; ----------------------------------------------------------------------------
CL_INH         equ  $01
CL_GEN0        equ  $02
CL_GEN8        equ  $03
CL_GEN16       equ  $04
CL_GEN32       equ  $05
CL_IMM8        equ  $06
CL_INDEXED     equ  $07
CL_REL         equ  $08
CL_RLIST       equ  $09
CL_RTOR        equ  $0A
CL_TFMRTOR     equ  $0B
CL_TFM         equ  $0C
CL_BITBIT      equ  $0D
CL_LOGICMEM    equ  $0E
CL_DIRECTIVE equ  $40
CL_ORG         equ  $40
CL_EQU         equ  $41
CL_SET         equ  $42
CL_SETDP       equ  $43
CL_FCB         equ  $44
CL_FDB         equ  $45
CL_FQB         equ  $46
CL_FCC         equ  $47
CL_FCN         equ  $48
CL_FCS         equ  $49
CL_RMB         equ  $4A
CL_RMD         equ  $4B
CL_RMQ         equ  $4C
CL_ZMB         equ  $4D
CL_ZMD         equ  $4E
CL_ZMQ         equ  $4F
CL_FILL        equ  $50
CL_ALIGN       equ  $51
CL_END         equ  $52
CL_INCLUDE     equ  $53
CL_INCLUDEBIN  equ  $54
CL_IFEQ        equ  $55
CL_IFNE        equ  $56
CL_IFGT        equ  $57
CL_IFGE        equ  $58
CL_IFLT        equ  $59
CL_IFLE        equ  $5A
CL_IFDEF       equ  $5B
CL_IFNDEF      equ  $5C
CL_ELSE        equ  $5D
CL_ENDC        equ  $5E
CL_MACRO       equ  $5F
CL_ENDM        equ  $60
CL_STRUCT      equ  $61
CL_ENDSTRUCT   equ  $62
CL_SECTION     equ  $63
CL_ENDSECTION  equ  $64
CL_EXPORT      equ  $65
CL_IMPORT      equ  $66
CL_EXTERN      equ  $67
CL_EXTDEP      equ  $68
CL_ERROR       equ  $69
CL_WARNING     equ  $6A
CL_NOOP        equ  $6B
CL_PRAGMA      equ  $6C
CL_STARPRAGMA  equ  $6D
CL_UNSUP     equ  $7F             ; a directive pugasm doesn't do
OF_COND        equ  $01
OF_ENDM        equ  $02
OF_SETSYM      equ  $04
OF_IS6309      equ  $08
OF_STRUCT      equ  $10
OF_SETDATA     equ  $20
OF_IS6809      equ  $40
OF_ORG         equ  $80
OPCOUNT      equ  340
; The entries' addresses, in name order.
OPINDEX
            FDB  OP_0
            FDB  OP_1
            FDB  OP_2
            FDB  OP_3
            FDB  OP_4
            FDB  OP_5
            FDB  OP_6
            FDB  OP_7
            FDB  OP_8
            FDB  OP_9
            FDB  OP_10
            FDB  OP_11
            FDB  OP_12
            FDB  OP_13
            FDB  OP_14
            FDB  OP_15
            FDB  OP_16
            FDB  OP_17
            FDB  OP_18
            FDB  OP_19
            FDB  OP_20
            FDB  OP_21
            FDB  OP_22
            FDB  OP_23
            FDB  OP_24
            FDB  OP_25
            FDB  OP_26
            FDB  OP_27
            FDB  OP_28
            FDB  OP_29
            FDB  OP_30
            FDB  OP_31
            FDB  OP_32
            FDB  OP_33
            FDB  OP_34
            FDB  OP_35
            FDB  OP_36
            FDB  OP_37
            FDB  OP_38
            FDB  OP_39
            FDB  OP_40
            FDB  OP_41
            FDB  OP_42
            FDB  OP_43
            FDB  OP_44
            FDB  OP_45
            FDB  OP_46
            FDB  OP_47
            FDB  OP_48
            FDB  OP_49
            FDB  OP_50
            FDB  OP_51
            FDB  OP_52
            FDB  OP_53
            FDB  OP_54
            FDB  OP_55
            FDB  OP_56
            FDB  OP_57
            FDB  OP_58
            FDB  OP_59
            FDB  OP_60
            FDB  OP_61
            FDB  OP_62
            FDB  OP_63
            FDB  OP_64
            FDB  OP_65
            FDB  OP_66
            FDB  OP_67
            FDB  OP_68
            FDB  OP_69
            FDB  OP_70
            FDB  OP_71
            FDB  OP_72
            FDB  OP_73
            FDB  OP_74
            FDB  OP_75
            FDB  OP_76
            FDB  OP_77
            FDB  OP_78
            FDB  OP_79
            FDB  OP_80
            FDB  OP_81
            FDB  OP_82
            FDB  OP_83
            FDB  OP_84
            FDB  OP_85
            FDB  OP_86
            FDB  OP_87
            FDB  OP_88
            FDB  OP_89
            FDB  OP_90
            FDB  OP_91
            FDB  OP_92
            FDB  OP_93
            FDB  OP_94
            FDB  OP_95
            FDB  OP_96
            FDB  OP_97
            FDB  OP_98
            FDB  OP_99
            FDB  OP_100
            FDB  OP_101
            FDB  OP_102
            FDB  OP_103
            FDB  OP_104
            FDB  OP_105
            FDB  OP_106
            FDB  OP_107
            FDB  OP_108
            FDB  OP_109
            FDB  OP_110
            FDB  OP_111
            FDB  OP_112
            FDB  OP_113
            FDB  OP_114
            FDB  OP_115
            FDB  OP_116
            FDB  OP_117
            FDB  OP_118
            FDB  OP_119
            FDB  OP_120
            FDB  OP_121
            FDB  OP_122
            FDB  OP_123
            FDB  OP_124
            FDB  OP_125
            FDB  OP_126
            FDB  OP_127
            FDB  OP_128
            FDB  OP_129
            FDB  OP_130
            FDB  OP_131
            FDB  OP_132
            FDB  OP_133
            FDB  OP_134
            FDB  OP_135
            FDB  OP_136
            FDB  OP_137
            FDB  OP_138
            FDB  OP_139
            FDB  OP_140
            FDB  OP_141
            FDB  OP_142
            FDB  OP_143
            FDB  OP_144
            FDB  OP_145
            FDB  OP_146
            FDB  OP_147
            FDB  OP_148
            FDB  OP_149
            FDB  OP_150
            FDB  OP_151
            FDB  OP_152
            FDB  OP_153
            FDB  OP_154
            FDB  OP_155
            FDB  OP_156
            FDB  OP_157
            FDB  OP_158
            FDB  OP_159
            FDB  OP_160
            FDB  OP_161
            FDB  OP_162
            FDB  OP_163
            FDB  OP_164
            FDB  OP_165
            FDB  OP_166
            FDB  OP_167
            FDB  OP_168
            FDB  OP_169
            FDB  OP_170
            FDB  OP_171
            FDB  OP_172
            FDB  OP_173
            FDB  OP_174
            FDB  OP_175
            FDB  OP_176
            FDB  OP_177
            FDB  OP_178
            FDB  OP_179
            FDB  OP_180
            FDB  OP_181
            FDB  OP_182
            FDB  OP_183
            FDB  OP_184
            FDB  OP_185
            FDB  OP_186
            FDB  OP_187
            FDB  OP_188
            FDB  OP_189
            FDB  OP_190
            FDB  OP_191
            FDB  OP_192
            FDB  OP_193
            FDB  OP_194
            FDB  OP_195
            FDB  OP_196
            FDB  OP_197
            FDB  OP_198
            FDB  OP_199
            FDB  OP_200
            FDB  OP_201
            FDB  OP_202
            FDB  OP_203
            FDB  OP_204
            FDB  OP_205
            FDB  OP_206
            FDB  OP_207
            FDB  OP_208
            FDB  OP_209
            FDB  OP_210
            FDB  OP_211
            FDB  OP_212
            FDB  OP_213
            FDB  OP_214
            FDB  OP_215
            FDB  OP_216
            FDB  OP_217
            FDB  OP_218
            FDB  OP_219
            FDB  OP_220
            FDB  OP_221
            FDB  OP_222
            FDB  OP_223
            FDB  OP_224
            FDB  OP_225
            FDB  OP_226
            FDB  OP_227
            FDB  OP_228
            FDB  OP_229
            FDB  OP_230
            FDB  OP_231
            FDB  OP_232
            FDB  OP_233
            FDB  OP_234
            FDB  OP_235
            FDB  OP_236
            FDB  OP_237
            FDB  OP_238
            FDB  OP_239
            FDB  OP_240
            FDB  OP_241
            FDB  OP_242
            FDB  OP_243
            FDB  OP_244
            FDB  OP_245
            FDB  OP_246
            FDB  OP_247
            FDB  OP_248
            FDB  OP_249
            FDB  OP_250
            FDB  OP_251
            FDB  OP_252
            FDB  OP_253
            FDB  OP_254
            FDB  OP_255
            FDB  OP_256
            FDB  OP_257
            FDB  OP_258
            FDB  OP_259
            FDB  OP_260
            FDB  OP_261
            FDB  OP_262
            FDB  OP_263
            FDB  OP_264
            FDB  OP_265
            FDB  OP_266
            FDB  OP_267
            FDB  OP_268
            FDB  OP_269
            FDB  OP_270
            FDB  OP_271
            FDB  OP_272
            FDB  OP_273
            FDB  OP_274
            FDB  OP_275
            FDB  OP_276
            FDB  OP_277
            FDB  OP_278
            FDB  OP_279
            FDB  OP_280
            FDB  OP_281
            FDB  OP_282
            FDB  OP_283
            FDB  OP_284
            FDB  OP_285
            FDB  OP_286
            FDB  OP_287
            FDB  OP_288
            FDB  OP_289
            FDB  OP_290
            FDB  OP_291
            FDB  OP_292
            FDB  OP_293
            FDB  OP_294
            FDB  OP_295
            FDB  OP_296
            FDB  OP_297
            FDB  OP_298
            FDB  OP_299
            FDB  OP_300
            FDB  OP_301
            FDB  OP_302
            FDB  OP_303
            FDB  OP_304
            FDB  OP_305
            FDB  OP_306
            FDB  OP_307
            FDB  OP_308
            FDB  OP_309
            FDB  OP_310
            FDB  OP_311
            FDB  OP_312
            FDB  OP_313
            FDB  OP_314
            FDB  OP_315
            FDB  OP_316
            FDB  OP_317
            FDB  OP_318
            FDB  OP_319
            FDB  OP_320
            FDB  OP_321
            FDB  OP_322
            FDB  OP_323
            FDB  OP_324
            FDB  OP_325
            FDB  OP_326
            FDB  OP_327
            FDB  OP_328
            FDB  OP_329
            FDB  OP_330
            FDB  OP_331
            FDB  OP_332
            FDB  OP_333
            FDB  OP_334
            FDB  OP_335
            FDB  OP_336
            FDB  OP_337
            FDB  OP_338
            FDB  OP_339
OP_0        FCB  8,'*','*','P','R','A','G','M','A'
            FCB  $6D,$00
OP_1        FCB  7,'*','P','R','A','G','M','A'
            FCB  $6D,$00
OP_2        FCB  10,'*','P','R','A','G','M','A','P','O','P'
            FCB  $6D,$00
OP_3        FCB  11,'*','P','R','A','G','M','A','P','U','S','H'
            FCB  $6D,$00
OP_4        FCB  6,'.','4','B','Y','T','E'
            FCB  $46,$00
OP_5        FCB  5,'.','A','R','E','A'
            FCB  $63,$00
OP_6        FCB  6,'.','A','S','C','I','I'
            FCB  $47,$00
OP_7        FCB  6,'.','A','S','C','I','S'
            FCB  $49,$00
OP_8        FCB  6,'.','A','S','C','I','Z'
            FCB  $48,$00
OP_9        FCB  5,'.','B','A','N','K'
            FCB  $6B,$00
OP_10       FCB  5,'.','B','L','K','B'
            FCB  $4A,$30
OP_11       FCB  5,'.','B','Y','T','E'
            FCB  $44,$00
OP_12       FCB  3,'.','D','B'
            FCB  $44,$00
OP_13       FCB  3,'.','D','S'
            FCB  $4A,$30
OP_14       FCB  3,'.','D','W'
            FCB  $45,$00
OP_15       FCB  4,'.','E','N','D'
            FCB  $52,$00
OP_16       FCB  6,'.','G','L','O','B','L'
            FCB  $65,$00
OP_17       FCB  7,'.','M','O','D','U','L','E'
            FCB  $6B,$00
OP_18       FCB  5,'.','Q','U','A','D'
            FCB  $46,$00
OP_19       FCB  3,'.','R','S'
            FCB  $4A,$30
OP_20       FCB  4,'.','S','T','R'
            FCB  $47,$00
OP_21       FCB  5,'.','S','T','R','S'
            FCB  $49,$00
OP_22       FCB  5,'.','S','T','R','Z'
            FCB  $48,$00
OP_23       FCB  5,'.','W','O','R','D'
            FCB  $45,$00
OP_24       FCB  1,'='
            FCB  $41,$04
OP_25       FCB  3,'A','B','X'
            FCB  $01,$00
            FDB  $003A,$FFFF,$FFFF,$FFFF
OP_26       FCB  4,'A','D','C','A'
            FCB  $03,$00
            FDB  $0099,$00A9,$00B9,$0089
OP_27       FCB  4,'A','D','C','B'
            FCB  $03,$00
            FDB  $00D9,$00E9,$00F9,$00C9
OP_28       FCB  4,'A','D','C','D'
            FCB  $04,$08
            FDB  $1099,$10A9,$10B9,$1089
OP_29       FCB  4,'A','D','C','R'
            FCB  $0A,$08
            FDB  $1031,$FFFF,$FFFF,$FFFF
OP_30       FCB  4,'A','D','D','A'
            FCB  $03,$00
            FDB  $009B,$00AB,$00BB,$008B
OP_31       FCB  4,'A','D','D','B'
            FCB  $03,$00
            FDB  $00DB,$00EB,$00FB,$00CB
OP_32       FCB  4,'A','D','D','D'
            FCB  $04,$00
            FDB  $00D3,$00E3,$00F3,$00C3
OP_33       FCB  4,'A','D','D','E'
            FCB  $03,$08
            FDB  $119B,$11AB,$11BB,$118B
OP_34       FCB  4,'A','D','D','F'
            FCB  $03,$08
            FDB  $11DB,$11EB,$11FB,$11CB
OP_35       FCB  4,'A','D','D','R'
            FCB  $0A,$08
            FDB  $1030,$FFFF,$FFFF,$FFFF
OP_36       FCB  4,'A','D','D','W'
            FCB  $04,$08
            FDB  $109B,$10AB,$10BB,$108B
OP_37       FCB  3,'A','I','M'
            FCB  $0E,$08
            FDB  $0002,$0062,$0072,$FFFF
OP_38       FCB  5,'A','L','I','G','N'
            FCB  $51,$00
OP_39       FCB  4,'A','N','D','A'
            FCB  $03,$00
            FDB  $0094,$00A4,$00B4,$0084
OP_40       FCB  4,'A','N','D','B'
            FCB  $03,$00
            FDB  $00D4,$00E4,$00F4,$00C4
OP_41       FCB  5,'A','N','D','C','C'
            FCB  $06,$00
            FDB  $001C,$FFFF,$FFFF,$001C
OP_42       FCB  4,'A','N','D','D'
            FCB  $04,$08
            FDB  $1094,$10A4,$10B4,$1084
OP_43       FCB  4,'A','N','D','R'
            FCB  $0A,$08
            FDB  $1034,$FFFF,$FFFF,$FFFF
OP_44       FCB  3,'A','S','L'
            FCB  $02,$00
            FDB  $0008,$0068,$0078,$FFFF
OP_45       FCB  4,'A','S','L','A'
            FCB  $01,$00
            FDB  $0048,$FFFF,$FFFF,$FFFF
OP_46       FCB  4,'A','S','L','B'
            FCB  $01,$00
            FDB  $0058,$FFFF,$FFFF,$FFFF
OP_47       FCB  4,'A','S','L','D'
            FCB  $01,$08
            FDB  $1048,$FFFF,$FFFF,$FFFF
OP_48       FCB  3,'A','S','R'
            FCB  $02,$00
            FDB  $0007,$0067,$0077,$FFFF
OP_49       FCB  4,'A','S','R','A'
            FCB  $01,$00
            FDB  $0047,$FFFF,$FFFF,$FFFF
OP_50       FCB  4,'A','S','R','B'
            FCB  $01,$00
            FDB  $0057,$FFFF,$FFFF,$FFFF
OP_51       FCB  4,'A','S','R','D'
            FCB  $01,$08
            FDB  $1047,$FFFF,$FFFF,$FFFF
OP_52       FCB  4,'B','A','N','D'
            FCB  $0D,$08
            FDB  $1130,$FFFF,$FFFF,$FFFF
OP_53       FCB  3,'B','C','C'
            FCB  $08,$00
            FDB  $0024,$0008,$0024,$1024
OP_54       FCB  3,'B','C','S'
            FCB  $08,$00
            FDB  $0025,$0008,$0025,$1025
OP_55       FCB  4,'B','E','O','R'
            FCB  $0D,$08
            FDB  $1134,$FFFF,$FFFF,$FFFF
OP_56       FCB  3,'B','E','Q'
            FCB  $08,$00
            FDB  $0027,$0008,$0027,$1027
OP_57       FCB  3,'B','G','E'
            FCB  $08,$00
            FDB  $002C,$0008,$002C,$102C
OP_58       FCB  3,'B','G','T'
            FCB  $08,$00
            FDB  $002E,$0008,$002E,$102E
OP_59       FCB  3,'B','H','I'
            FCB  $08,$00
            FDB  $0022,$0008,$0022,$1022
OP_60       FCB  3,'B','H','S'
            FCB  $08,$00
            FDB  $0024,$0008,$0024,$1024
OP_61       FCB  5,'B','I','A','N','D'
            FCB  $0D,$08
            FDB  $1131,$FFFF,$FFFF,$FFFF
OP_62       FCB  5,'B','I','E','O','R'
            FCB  $0D,$08
            FDB  $1135,$FFFF,$FFFF,$FFFF
OP_63       FCB  4,'B','I','O','R'
            FCB  $0D,$08
            FDB  $1133,$FFFF,$FFFF,$FFFF
OP_64       FCB  4,'B','I','T','A'
            FCB  $03,$00
            FDB  $0095,$00A5,$00B5,$0085
OP_65       FCB  4,'B','I','T','B'
            FCB  $03,$00
            FDB  $00D5,$00E5,$00F5,$00C5
OP_66       FCB  4,'B','I','T','D'
            FCB  $04,$08
            FDB  $1095,$10A5,$10B5,$1085
OP_67       FCB  5,'B','I','T','M','D'
            FCB  $06,$08
            FDB  $113C,$FFFF,$FFFF,$113C
OP_68       FCB  3,'B','L','E'
            FCB  $08,$00
            FDB  $002F,$0008,$002F,$102F
OP_69       FCB  3,'B','L','O'
            FCB  $08,$00
            FDB  $0025,$0008,$0025,$1025
OP_70       FCB  3,'B','L','S'
            FCB  $08,$00
            FDB  $0023,$0008,$0023,$1023
OP_71       FCB  3,'B','L','T'
            FCB  $08,$00
            FDB  $002D,$0008,$002D,$102D
OP_72       FCB  3,'B','M','I'
            FCB  $08,$00
            FDB  $002B,$0008,$002B,$102B
OP_73       FCB  3,'B','N','E'
            FCB  $08,$00
            FDB  $0026,$0008,$0026,$1026
OP_74       FCB  3,'B','O','R'
            FCB  $0D,$08
            FDB  $1132,$FFFF,$FFFF,$FFFF
OP_75       FCB  3,'B','P','L'
            FCB  $08,$00
            FDB  $002A,$0008,$002A,$102A
OP_76       FCB  3,'B','R','A'
            FCB  $08,$00
            FDB  $0020,$0008,$0020,$0016
OP_77       FCB  3,'B','R','N'
            FCB  $08,$00
            FDB  $0021,$0008,$0021,$1021
OP_78       FCB  3,'B','S','R'
            FCB  $08,$00
            FDB  $008D,$0008,$008D,$0017
OP_79       FCB  3,'B','S','Z'
            FCB  $4D,$00
OP_80       FCB  3,'B','V','C'
            FCB  $08,$00
            FDB  $0028,$0008,$0028,$1028
OP_81       FCB  3,'B','V','S'
            FCB  $08,$00
            FDB  $0029,$0008,$0029,$1029
OP_82       FCB  3,'C','L','R'
            FCB  $02,$00
            FDB  $000F,$006F,$007F,$FFFF
OP_83       FCB  4,'C','L','R','A'
            FCB  $01,$00
            FDB  $004F,$FFFF,$FFFF,$FFFF
OP_84       FCB  4,'C','L','R','B'
            FCB  $01,$00
            FDB  $005F,$FFFF,$FFFF,$FFFF
OP_85       FCB  4,'C','L','R','D'
            FCB  $01,$08
            FDB  $104F,$FFFF,$FFFF,$FFFF
OP_86       FCB  4,'C','L','R','E'
            FCB  $01,$08
            FDB  $114F,$FFFF,$FFFF,$FFFF
OP_87       FCB  4,'C','L','R','F'
            FCB  $01,$08
            FDB  $115F,$FFFF,$FFFF,$FFFF
OP_88       FCB  4,'C','L','R','W'
            FCB  $01,$08
            FDB  $105F,$FFFF,$FFFF,$FFFF
OP_89       FCB  4,'C','M','P','A'
            FCB  $03,$00
            FDB  $0091,$00A1,$00B1,$0081
OP_90       FCB  4,'C','M','P','B'
            FCB  $03,$00
            FDB  $00D1,$00E1,$00F1,$00C1
OP_91       FCB  4,'C','M','P','D'
            FCB  $04,$00
            FDB  $1093,$10A3,$10B3,$1083
OP_92       FCB  4,'C','M','P','E'
            FCB  $03,$08
            FDB  $1191,$11A1,$11B1,$1181
OP_93       FCB  4,'C','M','P','F'
            FCB  $03,$08
            FDB  $11D1,$11E1,$11F1,$11C1
OP_94       FCB  4,'C','M','P','R'
            FCB  $0A,$08
            FDB  $1037,$FFFF,$FFFF,$FFFF
OP_95       FCB  4,'C','M','P','S'
            FCB  $04,$00
            FDB  $119C,$11AC,$11BC,$118C
OP_96       FCB  4,'C','M','P','U'
            FCB  $04,$00
            FDB  $1193,$11A3,$11B3,$1183
OP_97       FCB  4,'C','M','P','W'
            FCB  $04,$08
            FDB  $1091,$10A1,$10B1,$1081
OP_98       FCB  4,'C','M','P','X'
            FCB  $04,$00
            FDB  $009C,$00AC,$00BC,$008C
OP_99       FCB  4,'C','M','P','Y'
            FCB  $04,$00
            FDB  $109C,$10AC,$10BC,$108C
OP_100      FCB  3,'C','O','M'
            FCB  $02,$00
            FDB  $0003,$0063,$0073,$FFFF
OP_101      FCB  4,'C','O','M','A'
            FCB  $01,$00
            FDB  $0043,$FFFF,$FFFF,$FFFF
OP_102      FCB  4,'C','O','M','B'
            FCB  $01,$00
            FDB  $0053,$FFFF,$FFFF,$FFFF
OP_103      FCB  4,'C','O','M','D'
            FCB  $01,$08
            FDB  $1043,$FFFF,$FFFF,$FFFF
OP_104      FCB  4,'C','O','M','E'
            FCB  $01,$08
            FDB  $1143,$FFFF,$FFFF,$FFFF
OP_105      FCB  4,'C','O','M','F'
            FCB  $01,$08
            FDB  $1153,$FFFF,$FFFF,$FFFF
OP_106      FCB  4,'C','O','M','W'
            FCB  $01,$08
            FDB  $1053,$FFFF,$FFFF,$FFFF
OP_107      FCB  4,'C','O','P','Y'
            FCB  $0B,$08
            FDB  $1138,$FFFF,$FFFF,$FFFF
OP_108      FCB  5,'C','O','P','Y','+'
            FCB  $0B,$08
            FDB  $1138,$FFFF,$FFFF,$FFFF
OP_109      FCB  5,'C','O','P','Y','-'
            FCB  $0B,$08
            FDB  $1139,$FFFF,$FFFF,$FFFF
OP_110      FCB  4,'C','W','A','I'
            FCB  $06,$00
            FDB  $003C,$FFFF,$FFFF,$FFFF
OP_111      FCB  3,'D','A','A'
            FCB  $01,$00
            FDB  $0019,$FFFF,$FFFF,$FFFF
OP_112      FCB  3,'D','E','C'
            FCB  $02,$00
            FDB  $000A,$006A,$007A,$FFFF
OP_113      FCB  4,'D','E','C','A'
            FCB  $01,$00
            FDB  $004A,$FFFF,$FFFF,$FFFF
OP_114      FCB  4,'D','E','C','B'
            FCB  $01,$00
            FDB  $005A,$FFFF,$FFFF,$FFFF
OP_115      FCB  4,'D','E','C','D'
            FCB  $01,$08
            FDB  $104A,$FFFF,$FFFF,$FFFF
OP_116      FCB  4,'D','E','C','E'
            FCB  $01,$08
            FDB  $114A,$FFFF,$FFFF,$FFFF
OP_117      FCB  4,'D','E','C','F'
            FCB  $01,$08
            FDB  $115A,$FFFF,$FFFF,$FFFF
OP_118      FCB  4,'D','E','C','W'
            FCB  $01,$08
            FDB  $105A,$FFFF,$FFFF,$FFFF
OP_119      FCB  4,'D','I','V','D'
            FCB  $03,$08
            FDB  $119D,$11AD,$11BD,$118D
OP_120      FCB  4,'D','I','V','Q'
            FCB  $04,$08
            FDB  $119E,$11AE,$11BE,$118E
OP_121      FCB  3,'D','T','B'
            FCB  $7F,$00
OP_122      FCB  3,'D','T','S'
            FCB  $7F,$00
OP_123      FCB  3,'E','I','M'
            FCB  $0E,$08
            FDB  $0005,$0065,$0075,$FFFF
OP_124      FCB  4,'E','L','S','E'
            FCB  $5D,$01
OP_125      FCB  4,'E','M','O','D'
            FCB  $7F,$00
OP_126      FCB  3,'E','N','D'
            FCB  $52,$00
OP_127      FCB  4,'E','N','D','C'
            FCB  $5E,$01
OP_128      FCB  5,'E','N','D','I','F'
            FCB  $5E,$01
OP_129      FCB  4,'E','N','D','M'
            FCB  $60,$07
OP_130      FCB  4,'E','N','D','S'
            FCB  $62,$10
OP_131      FCB  7,'E','N','D','S','E','C','T'
            FCB  $64,$00
OP_132      FCB  10,'E','N','D','S','E','C','T','I','O','N'
            FCB  $64,$00
OP_133      FCB  9,'E','N','D','S','T','R','U','C','T'
            FCB  $62,$10
OP_134      FCB  4,'E','O','R','A'
            FCB  $03,$00
            FDB  $0098,$00A8,$00B8,$0088
OP_135      FCB  4,'E','O','R','B'
            FCB  $03,$00
            FDB  $00D8,$00E8,$00F8,$00C8
OP_136      FCB  4,'E','O','R','D'
            FCB  $04,$08
            FDB  $1098,$10A8,$10B8,$1088
OP_137      FCB  4,'E','O','R','R'
            FCB  $0A,$08
            FDB  $1036,$FFFF,$FFFF,$FFFF
OP_138      FCB  3,'E','Q','U'
            FCB  $41,$04
OP_139      FCB  5,'E','R','R','O','R'
            FCB  $69,$00
OP_140      FCB  3,'E','X','G'
            FCB  $0A,$00
            FDB  $001E,$FFFF,$FFFF,$FFFF
OP_141      FCB  3,'E','X','P'
            FCB  $0B,$08
            FDB  $113B,$FFFF,$FFFF,$FFFF
OP_142      FCB  6,'E','X','P','A','N','D'
            FCB  $0B,$08
            FDB  $113B,$FFFF,$FFFF,$FFFF
OP_143      FCB  6,'E','X','P','O','R','T'
            FCB  $65,$04
OP_144      FCB  6,'E','X','T','D','E','P'
            FCB  $68,$04
OP_145      FCB  6,'E','X','T','E','R','N'
            FCB  $67,$04
OP_146      FCB  8,'E','X','T','E','R','N','A','L'
            FCB  $67,$04
OP_147      FCB  3,'F','C','B'
            FCB  $44,$00
OP_148      FCB  3,'F','C','C'
            FCB  $47,$00
OP_149      FCB  3,'F','C','N'
            FCB  $48,$00
OP_150      FCB  3,'F','C','S'
            FCB  $49,$00
OP_151      FCB  3,'F','C','Z'
            FCB  $48,$00
OP_152      FCB  3,'F','D','B'
            FCB  $45,$00
OP_153      FCB  4,'F','D','B','S'
            FCB  $7F,$00
OP_154      FCB  4,'F','I','L','L'
            FCB  $50,$00
OP_155      FCB  3,'F','Q','B'
            FCB  $46,$00
OP_156      FCB  3,'F','Z','B'
            FCB  $4D,$00
OP_157      FCB  3,'H','C','F'
            FCB  $01,$40
            FDB  $0014,$FFFF,$FFFF,$FFFF
OP_158      FCB  2,'I','F'
            FCB  $56,$01
OP_159      FCB  5,'I','F','D','E','F'
            FCB  $5B,$01
OP_160      FCB  4,'I','F','E','Q'
            FCB  $55,$01
OP_161      FCB  4,'I','F','G','E'
            FCB  $58,$01
OP_162      FCB  4,'I','F','G','T'
            FCB  $57,$01
OP_163      FCB  4,'I','F','L','E'
            FCB  $5A,$01
OP_164      FCB  4,'I','F','L','T'
            FCB  $59,$01
OP_165      FCB  6,'I','F','N','D','E','F'
            FCB  $5C,$01
OP_166      FCB  4,'I','F','N','E'
            FCB  $56,$01
OP_167      FCB  5,'I','F','O','P','T'
            FCB  $7F,$01
OP_168      FCB  4,'I','F','P','1'
            FCB  $7F,$01
OP_169      FCB  4,'I','F','P','2'
            FCB  $7F,$01
OP_170      FCB  8,'I','F','P','R','A','G','M','A'
            FCB  $7F,$01
OP_171      FCB  5,'I','F','S','T','R'
            FCB  $7F,$01
OP_172      FCB  3,'I','M','P'
            FCB  $0B,$08
            FDB  $113A,$FFFF,$FFFF,$FFFF
OP_173      FCB  7,'I','M','P','L','O','D','E'
            FCB  $0B,$08
            FDB  $113A,$FFFF,$FFFF,$FFFF
OP_174      FCB  6,'I','M','P','O','R','T'
            FCB  $67,$04
OP_175      FCB  3,'I','N','C'
            FCB  $02,$00
            FDB  $000C,$006C,$007C,$FFFF
OP_176      FCB  4,'I','N','C','A'
            FCB  $01,$00
            FDB  $004C,$FFFF,$FFFF,$FFFF
OP_177      FCB  4,'I','N','C','B'
            FCB  $01,$00
            FDB  $005C,$FFFF,$FFFF,$FFFF
OP_178      FCB  4,'I','N','C','D'
            FCB  $01,$08
            FDB  $104C,$FFFF,$FFFF,$FFFF
OP_179      FCB  4,'I','N','C','E'
            FCB  $01,$08
            FDB  $114C,$FFFF,$FFFF,$FFFF
OP_180      FCB  4,'I','N','C','F'
            FCB  $01,$08
            FDB  $115C,$FFFF,$FFFF,$FFFF
OP_181      FCB  4,'I','N','C','L'
            FCB  $53,$00
OP_182      FCB  7,'I','N','C','L','U','D','E'
            FCB  $53,$00
OP_183      FCB  10,'I','N','C','L','U','D','E','B','I','N'
            FCB  $54,$00
OP_184      FCB  10,'I','N','C','L','U','D','E','S','T','R'
            FCB  $7F,$00
OP_185      FCB  4,'I','N','C','W'
            FCB  $01,$08
            FDB  $105C,$FFFF,$FFFF,$FFFF
OP_186      FCB  3,'J','M','P'
            FCB  $02,$00
            FDB  $000E,$006E,$007E,$FFFF
OP_187      FCB  3,'J','S','R'
            FCB  $02,$00
            FDB  $009D,$00AD,$00BD,$FFFF
OP_188      FCB  4,'L','B','C','C'
            FCB  $08,$00
            FDB  $1024,$0010,$0024,$1024
OP_189      FCB  4,'L','B','C','S'
            FCB  $08,$00
            FDB  $1025,$0010,$0025,$1025
OP_190      FCB  4,'L','B','E','Q'
            FCB  $08,$00
            FDB  $1027,$0010,$0027,$1027
OP_191      FCB  4,'L','B','G','E'
            FCB  $08,$00
            FDB  $102C,$0010,$002C,$102C
OP_192      FCB  4,'L','B','G','T'
            FCB  $08,$00
            FDB  $102E,$0010,$002E,$102E
OP_193      FCB  4,'L','B','H','I'
            FCB  $08,$00
            FDB  $1022,$0010,$0022,$1022
OP_194      FCB  4,'L','B','H','S'
            FCB  $08,$00
            FDB  $1024,$0010,$0024,$1024
OP_195      FCB  4,'L','B','L','E'
            FCB  $08,$00
            FDB  $102F,$0010,$002F,$102F
OP_196      FCB  4,'L','B','L','O'
            FCB  $08,$00
            FDB  $1025,$0010,$0025,$1025
OP_197      FCB  4,'L','B','L','S'
            FCB  $08,$00
            FDB  $1023,$0010,$0023,$1023
OP_198      FCB  4,'L','B','L','T'
            FCB  $08,$00
            FDB  $102D,$0010,$002D,$102D
OP_199      FCB  4,'L','B','M','I'
            FCB  $08,$00
            FDB  $102B,$0010,$002B,$102B
OP_200      FCB  4,'L','B','N','E'
            FCB  $08,$00
            FDB  $1026,$0010,$0026,$1026
OP_201      FCB  4,'L','B','P','L'
            FCB  $08,$00
            FDB  $102A,$0010,$002A,$102A
OP_202      FCB  4,'L','B','R','A'
            FCB  $08,$00
            FDB  $0016,$0010,$0020,$0016
OP_203      FCB  4,'L','B','R','N'
            FCB  $08,$00
            FDB  $1021,$0010,$0021,$1021
OP_204      FCB  4,'L','B','S','R'
            FCB  $08,$00
            FDB  $0017,$0010,$008D,$0017
OP_205      FCB  4,'L','B','V','C'
            FCB  $08,$00
            FDB  $1028,$0010,$0028,$1028
OP_206      FCB  4,'L','B','V','S'
            FCB  $08,$00
            FDB  $1029,$0010,$0029,$1029
OP_207      FCB  3,'L','D','A'
            FCB  $03,$00
            FDB  $0096,$00A6,$00B6,$0086
OP_208      FCB  3,'L','D','B'
            FCB  $03,$00
            FDB  $00D6,$00E6,$00F6,$00C6
OP_209      FCB  4,'L','D','B','T'
            FCB  $0D,$08
            FDB  $1136,$FFFF,$FFFF,$FFFF
OP_210      FCB  3,'L','D','D'
            FCB  $04,$00
            FDB  $00DC,$00EC,$00FC,$00CC
OP_211      FCB  3,'L','D','E'
            FCB  $03,$08
            FDB  $1196,$11A6,$11B6,$1186
OP_212      FCB  3,'L','D','F'
            FCB  $03,$08
            FDB  $11D6,$11E6,$11F6,$11C6
OP_213      FCB  4,'L','D','M','D'
            FCB  $06,$08
            FDB  $113D,$FFFF,$FFFF,$113D
OP_214      FCB  3,'L','D','Q'
            FCB  $05,$08
            FDB  $10DC,$10EC,$10FC,$00CD
OP_215      FCB  3,'L','D','S'
            FCB  $04,$00
            FDB  $10DE,$10EE,$10FE,$10CE
OP_216      FCB  3,'L','D','U'
            FCB  $04,$00
            FDB  $00DE,$00EE,$00FE,$00CE
OP_217      FCB  3,'L','D','W'
            FCB  $04,$08
            FDB  $1096,$10A6,$10B6,$1086
OP_218      FCB  3,'L','D','X'
            FCB  $04,$00
            FDB  $009E,$00AE,$00BE,$008E
OP_219      FCB  3,'L','D','Y'
            FCB  $04,$00
            FDB  $109E,$10AE,$10BE,$108E
OP_220      FCB  4,'L','E','A','S'
            FCB  $07,$00
            FDB  $0032,$FFFF,$FFFF,$FFFF
OP_221      FCB  4,'L','E','A','U'
            FCB  $07,$00
            FDB  $0033,$FFFF,$FFFF,$FFFF
OP_222      FCB  4,'L','E','A','X'
            FCB  $07,$00
            FDB  $0030,$FFFF,$FFFF,$FFFF
OP_223      FCB  4,'L','E','A','Y'
            FCB  $07,$00
            FDB  $0031,$FFFF,$FFFF,$FFFF
OP_224      FCB  3,'L','S','L'
            FCB  $02,$00
            FDB  $0008,$0068,$0078,$FFFF
OP_225      FCB  4,'L','S','L','A'
            FCB  $01,$00
            FDB  $0048,$FFFF,$FFFF,$FFFF
OP_226      FCB  4,'L','S','L','B'
            FCB  $01,$00
            FDB  $0058,$FFFF,$FFFF,$FFFF
OP_227      FCB  4,'L','S','L','D'
            FCB  $01,$08
            FDB  $1048,$FFFF,$FFFF,$FFFF
OP_228      FCB  3,'L','S','R'
            FCB  $02,$00
            FDB  $0004,$0064,$0074,$FFFF
OP_229      FCB  4,'L','S','R','A'
            FCB  $01,$00
            FDB  $0044,$FFFF,$FFFF,$FFFF
OP_230      FCB  4,'L','S','R','B'
            FCB  $01,$00
            FDB  $0054,$FFFF,$FFFF,$FFFF
OP_231      FCB  4,'L','S','R','D'
            FCB  $01,$08
            FDB  $1044,$FFFF,$FFFF,$FFFF
OP_232      FCB  4,'L','S','R','W'
            FCB  $01,$08
            FDB  $1054,$FFFF,$FFFF,$FFFF
OP_233      FCB  4,'M','A','C','R'
            FCB  $5F,$05
OP_234      FCB  5,'M','A','C','R','O'
            FCB  $5F,$05
OP_235      FCB  3,'M','O','D'
            FCB  $7F,$00
OP_236      FCB  3,'M','S','G'
            FCB  $6A,$00
OP_237      FCB  3,'M','U','L'
            FCB  $01,$00
            FDB  $003D,$FFFF,$FFFF,$FFFF
OP_238      FCB  4,'M','U','L','D'
            FCB  $04,$08
            FDB  $119F,$11AF,$11BF,$118F
OP_239      FCB  3,'N','A','M'
            FCB  $6B,$00
OP_240      FCB  3,'N','E','G'
            FCB  $02,$00
            FDB  $0000,$0060,$0070,$FFFF
OP_241      FCB  4,'N','E','G','A'
            FCB  $01,$00
            FDB  $0040,$FFFF,$FFFF,$FFFF
OP_242      FCB  4,'N','E','G','B'
            FCB  $01,$00
            FDB  $0050,$FFFF,$FFFF,$FFFF
OP_243      FCB  4,'N','E','G','D'
            FCB  $01,$08
            FDB  $1040,$FFFF,$FFFF,$FFFF
OP_244      FCB  3,'N','O','P'
            FCB  $01,$00
            FDB  $0012,$FFFF,$FFFF,$FFFF
OP_245      FCB  3,'O','I','M'
            FCB  $0E,$08
            FDB  $0001,$0061,$0071,$FFFF
OP_246      FCB  3,'O','P','T'
            FCB  $6D,$00
OP_247      FCB  3,'O','R','A'
            FCB  $03,$00
            FDB  $009A,$00AA,$00BA,$008A
OP_248      FCB  3,'O','R','B'
            FCB  $03,$00
            FDB  $00DA,$00EA,$00FA,$00CA
OP_249      FCB  4,'O','R','C','C'
            FCB  $06,$00
            FDB  $001A,$FFFF,$FFFF,$001A
OP_250      FCB  3,'O','R','D'
            FCB  $04,$08
            FDB  $109A,$10AA,$10BA,$108A
OP_251      FCB  3,'O','R','G'
            FCB  $40,$80
OP_252      FCB  3,'O','R','R'
            FCB  $0A,$08
            FDB  $1035,$FFFF,$FFFF,$FFFF
OP_253      FCB  3,'O','S','9'
            FCB  $7F,$00
OP_254      FCB  3,'P','A','G'
            FCB  $6B,$00
OP_255      FCB  4,'P','A','G','E'
            FCB  $6B,$00
OP_256      FCB  6,'P','R','A','G','M','A'
            FCB  $6C,$00
OP_257      FCB  4,'P','S','H','S'
            FCB  $09,$00
            FDB  $0034,$FFFF,$FFFF,$FFFF
OP_258      FCB  5,'P','S','H','S','W'
            FCB  $01,$08
            FDB  $1038,$FFFF,$FFFF,$FFFF
OP_259      FCB  4,'P','S','H','U'
            FCB  $09,$00
            FDB  $0036,$FFFF,$FFFF,$FFFF
OP_260      FCB  5,'P','S','H','U','W'
            FCB  $01,$08
            FDB  $103A,$FFFF,$FFFF,$FFFF
OP_261      FCB  4,'P','U','L','S'
            FCB  $09,$00
            FDB  $0035,$FFFF,$FFFF,$FFFF
OP_262      FCB  5,'P','U','L','S','W'
            FCB  $01,$08
            FDB  $1039,$FFFF,$FFFF,$FFFF
OP_263      FCB  4,'P','U','L','U'
            FCB  $09,$00
            FDB  $0037,$FFFF,$FFFF,$FFFF
OP_264      FCB  5,'P','U','L','U','W'
            FCB  $01,$08
            FDB  $103B,$FFFF,$FFFF,$FFFF
OP_265      FCB  5,'R','E','O','R','G'
            FCB  $7F,$00
OP_266      FCB  5,'R','E','S','E','T'
            FCB  $01,$40
            FDB  $003E,$FFFF,$FFFF,$FFFF
OP_267      FCB  3,'R','H','F'
            FCB  $01,$40
            FDB  $0014,$FFFF,$FFFF,$FFFF
OP_268      FCB  3,'R','M','B'
            FCB  $4A,$30
OP_269      FCB  3,'R','M','D'
            FCB  $4B,$30
OP_270      FCB  3,'R','M','Q'
            FCB  $4C,$30
OP_271      FCB  3,'R','M','W'
            FCB  $4B,$30
OP_272      FCB  3,'R','O','L'
            FCB  $02,$00
            FDB  $0009,$0069,$0079,$FFFF
OP_273      FCB  4,'R','O','L','A'
            FCB  $01,$00
            FDB  $0049,$FFFF,$FFFF,$FFFF
OP_274      FCB  4,'R','O','L','B'
            FCB  $01,$00
            FDB  $0059,$FFFF,$FFFF,$FFFF
OP_275      FCB  4,'R','O','L','D'
            FCB  $01,$08
            FDB  $1049,$FFFF,$FFFF,$FFFF
OP_276      FCB  4,'R','O','L','W'
            FCB  $01,$08
            FDB  $1059,$FFFF,$FFFF,$FFFF
OP_277      FCB  3,'R','O','R'
            FCB  $02,$00
            FDB  $0006,$0066,$0076,$FFFF
OP_278      FCB  4,'R','O','R','A'
            FCB  $01,$00
            FDB  $0046,$FFFF,$FFFF,$FFFF
OP_279      FCB  4,'R','O','R','B'
            FCB  $01,$00
            FDB  $0056,$FFFF,$FFFF,$FFFF
OP_280      FCB  4,'R','O','R','D'
            FCB  $01,$08
            FDB  $1046,$FFFF,$FFFF,$FFFF
OP_281      FCB  4,'R','O','R','W'
            FCB  $01,$08
            FDB  $1056,$FFFF,$FFFF,$FFFF
OP_282      FCB  3,'R','T','I'
            FCB  $01,$00
            FDB  $003B,$FFFF,$FFFF,$FFFF
OP_283      FCB  3,'R','T','S'
            FCB  $01,$00
            FDB  $0039,$FFFF,$FFFF,$FFFF
OP_284      FCB  4,'S','B','C','A'
            FCB  $03,$00
            FDB  $0092,$00A2,$00B2,$0082
OP_285      FCB  4,'S','B','C','B'
            FCB  $03,$00
            FDB  $00D2,$00E2,$00F2,$00C2
OP_286      FCB  4,'S','B','C','D'
            FCB  $04,$08
            FDB  $1092,$10A2,$10B2,$1082
OP_287      FCB  4,'S','B','C','R'
            FCB  $0A,$08
            FDB  $1033,$FFFF,$FFFF,$FFFF
OP_288      FCB  4,'S','E','C','T'
            FCB  $63,$00
OP_289      FCB  7,'S','E','C','T','I','O','N'
            FCB  $63,$00
OP_290      FCB  3,'S','E','T'
            FCB  $42,$04
OP_291      FCB  5,'S','E','T','D','P'
            FCB  $43,$00
OP_292      FCB  6,'S','E','T','S','T','R'
            FCB  $7F,$00
OP_293      FCB  3,'S','E','X'
            FCB  $01,$00
            FDB  $001D,$FFFF,$FFFF,$FFFF
OP_294      FCB  4,'S','E','X','W'
            FCB  $01,$08
            FDB  $0014,$FFFF,$FFFF,$FFFF
OP_295      FCB  3,'S','P','C'
            FCB  $6B,$00
OP_296      FCB  3,'S','T','A'
            FCB  $02,$00
            FDB  $0097,$00A7,$00B7,$FFFF
OP_297      FCB  3,'S','T','B'
            FCB  $02,$00
            FDB  $00D7,$00E7,$00F7,$FFFF
OP_298      FCB  4,'S','T','B','T'
            FCB  $0D,$08
            FDB  $1137,$FFFF,$FFFF,$FFFF
OP_299      FCB  3,'S','T','D'
            FCB  $02,$00
            FDB  $00DD,$00ED,$00FD,$FFFF
OP_300      FCB  3,'S','T','E'
            FCB  $02,$08
            FDB  $1197,$11A7,$11B7,$FFFF
OP_301      FCB  3,'S','T','F'
            FCB  $02,$08
            FDB  $11D7,$11E7,$11F7,$FFFF
OP_302      FCB  3,'S','T','Q'
            FCB  $02,$08
            FDB  $10DD,$10ED,$10FD,$FFFF
OP_303      FCB  6,'S','T','R','U','C','T'
            FCB  $61,$00
OP_304      FCB  3,'S','T','S'
            FCB  $02,$00
            FDB  $10DF,$10EF,$10FF,$FFFF
OP_305      FCB  3,'S','T','U'
            FCB  $02,$00
            FDB  $00DF,$00EF,$00FF,$FFFF
OP_306      FCB  3,'S','T','W'
            FCB  $02,$08
            FDB  $1097,$10A7,$10B7,$FFFF
OP_307      FCB  3,'S','T','X'
            FCB  $02,$00
            FDB  $009F,$00AF,$00BF,$FFFF
OP_308      FCB  3,'S','T','Y'
            FCB  $02,$00
            FDB  $109F,$10AF,$10BF,$FFFF
OP_309      FCB  4,'S','U','B','A'
            FCB  $03,$00
            FDB  $0090,$00A0,$00B0,$0080
OP_310      FCB  4,'S','U','B','B'
            FCB  $03,$00
            FDB  $00D0,$00E0,$00F0,$00C0
OP_311      FCB  4,'S','U','B','D'
            FCB  $04,$00
            FDB  $0093,$00A3,$00B3,$0083
OP_312      FCB  4,'S','U','B','E'
            FCB  $03,$08
            FDB  $1190,$11A0,$11B0,$1180
OP_313      FCB  4,'S','U','B','F'
            FCB  $03,$08
            FDB  $11D0,$11E0,$11F0,$11C0
OP_314      FCB  4,'S','U','B','R'
            FCB  $0A,$08
            FDB  $1032,$FFFF,$FFFF,$FFFF
OP_315      FCB  4,'S','U','B','W'
            FCB  $04,$08
            FDB  $1090,$10A0,$10B0,$1080
OP_316      FCB  3,'S','W','I'
            FCB  $01,$00
            FDB  $003F,$FFFF,$FFFF,$FFFF
OP_317      FCB  4,'S','W','I','2'
            FCB  $01,$00
            FDB  $103F,$FFFF,$FFFF,$FFFF
OP_318      FCB  4,'S','W','I','3'
            FCB  $01,$00
            FDB  $113F,$FFFF,$FFFF,$FFFF
OP_319      FCB  4,'S','Y','N','C'
            FCB  $01,$00
            FDB  $0013,$FFFF,$FFFF,$FFFF
OP_320      FCB  3,'T','F','M'
            FCB  $0C,$08
            FDB  $1138,$1139,$113A,$113B
OP_321      FCB  3,'T','F','R'
            FCB  $0A,$00
            FDB  $001F,$FFFF,$FFFF,$FFFF
OP_322      FCB  4,'T','F','R','M'
            FCB  $0B,$08
            FDB  $1139,$FFFF,$FFFF,$FFFF
OP_323      FCB  4,'T','F','R','P'
            FCB  $0B,$08
            FDB  $1138,$FFFF,$FFFF,$FFFF
OP_324      FCB  4,'T','F','R','R'
            FCB  $0B,$08
            FDB  $113B,$FFFF,$FFFF,$FFFF
OP_325      FCB  4,'T','F','R','S'
            FCB  $0B,$08
            FDB  $113A,$FFFF,$FFFF,$FFFF
OP_326      FCB  3,'T','I','M'
            FCB  $0E,$08
            FDB  $000B,$006B,$007B,$FFFF
OP_327      FCB  3,'T','S','T'
            FCB  $02,$00
            FDB  $000D,$006D,$007D,$FFFF
OP_328      FCB  4,'T','S','T','A'
            FCB  $01,$00
            FDB  $004D,$FFFF,$FFFF,$FFFF
OP_329      FCB  4,'T','S','T','B'
            FCB  $01,$00
            FDB  $005D,$FFFF,$FFFF,$FFFF
OP_330      FCB  4,'T','S','T','D'
            FCB  $01,$08
            FDB  $104D,$FFFF,$FFFF,$FFFF
OP_331      FCB  4,'T','S','T','E'
            FCB  $01,$08
            FDB  $114D,$FFFF,$FFFF,$FFFF
OP_332      FCB  4,'T','S','T','F'
            FCB  $01,$08
            FDB  $115D,$FFFF,$FFFF,$FFFF
OP_333      FCB  4,'T','S','T','W'
            FCB  $01,$08
            FDB  $105D,$FFFF,$FFFF,$FFFF
OP_334      FCB  3,'T','T','L'
            FCB  $6B,$00
OP_335      FCB  3,'U','S','E'
            FCB  $53,$00
OP_336      FCB  7,'W','A','R','N','I','N','G'
            FCB  $6A,$00
OP_337      FCB  3,'Z','M','B'
            FCB  $4D,$00
OP_338      FCB  3,'Z','M','D'
            FCB  $4E,$00
OP_339      FCB  3,'Z','M','Q'
            FCB  $4F,$00
